### ISSUE TITLE
Fix image loading issues

### ISSUE THREAD

**Issue by Whatthee** [Willy-JL/F95Checker#107]
I keep getting this error
```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\threading.py", line 975, in run
  File "D:\a\F95Checker\F95Checker\modules\sync_thread.py", line 19, in run_loop
  File "D:\a\F95Checker\F95Checker\modules\imagehelper.py", line 112, in reload
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\Image.py", line 3277, in open
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\Image.py", line 3263, in _open_core
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\ImageFile.py", line 117, in __init__
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\PngImagePlugin.py", line 734, in _open
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\PngImagePlugin.py", line 203, in call
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\PngImagePlugin.py", line 569, in chunk_zTXt
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\PngImagePlugin.py", line 150, in _safe_zlib_decompress
ValueError: Decompressed Data Too Large
```
And I don't seem to be the only one, as someone posted [here](https://f95zone.to/threads/f95checker-willyjl.44173/post-12569076)

One solution might be to track the problematic image file(s), but it seems to suddenly affect almost all my images.

Someone seems to have an interesting solution, which might be worth checking up on [here](https://f95zone.to/threads/f95checker-willyjl.44173/post-12569921) with reference to [stackoverflow](https://stackoverflow.com/questions/42671252/python-pillow-valueerror-decompressed-data-too-large)

Thank you!

**Comment by GrammerCopper** [comment]
FYI - I am receiving the exact same error during application start up.

**Comment by GrammerCopper** [comment]
This may actually help a little...maybe. I received this error after I hovered over a single game.

`Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\threading.py", line 975, in run
  File "D:\a\F95Checker\F95Checker\modules\sync_thread.py", line 19, in run_loop
  File "D:\a\F95Checker\F95Checker\modules\imagehelper.py", line 112, in reload
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\Image.py", line 3277, in open
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\Image.py", line 3263, in _open_core
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\ImageFile.py", line 117, in __init__
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\PngImagePlugin.py", line 734, in _open
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\PngImagePlugin.py", line 203, in call
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\PngImagePlugin.py", line 569, in chunk_zTXt
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\PIL\PngImagePlugin.py", line 150, in _safe_zlib_decompress
ValueError: Decompressed Data Too Large
`
I had highlighted every game I had EXCEPT for the one game and it was fine. When I highlighted this game I received the error. I had also restarted the tool and highlighted ONLY this game and received the error. The game thread is:

https://f95zone.to/threads/succubus-summon-v1-1-crazysky3d.165448/

Hope this helps. Perhaps an error catch to ignore the game that causes the error.
