### ISSUE TITLE
'NoneType' object has no attribute 'minimized'

### ISSUE THREAD

**Issue by just-Addict** [Willy-JL/F95Checker#14]
Getting this when running the windows exe, same error when running from source, only difference being the paths to the various files are different...

```Traceback (most recent call last):
  File "D:\a\F95Checker\F95Checker\src\modules\db.py", line 441, in migrate_legacy
KeyError: ' none'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\F95Checker\F95Checker\cx_Freeze\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "D:\a\F95Checker\F95Checker\cx_Freeze\cx_Freeze\initscripts\Console.py", line 15, in run
  File "D:\a\F95Checker\F95Checker\src\main.py", line 78, in <module>
  File "D:\a\F95Checker\F95Checker\src\main.py", line 45, in main
  File "D:\a\F95Checker\F95Checker\src\modules\async_thread.py", line 37, in wait
  File "D:\a\F95Checker\F95Checker\src\modules\db.py", line 122, in connect
  File "D:\a\F95Checker\F95Checker\src\modules\db.py", line 497, in migrate_legacy
  File "D:\a\F95Checker\F95Checker\src\modules\utils.py", line 292, in push_popup
AttributeError: 'NoneType' object has no attribute 'minimized'
```

**Comment by Willy-JL** [comment]
Ok now that is a very good catch, a problem in migrating old configs. I understand the problem, shouldn't take too much to fix but I'll do it tomorrow, today's been a long day :D
