### ISSUE TITLE
thread parsing errors during refresh

### ISSUE THREAD

**Issue by TechKen1** [Willy-JL/F95Checker#169]
Traceback (most recent call last):
  File "D:\a\F95Checker\F95Checker\modules\parser.py", line 307, in thread
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\enum.py", line 795, in __getitem__
KeyError: 'asset-daz-gen3'

same issue is also happening with "asset-daz-gen2"

**Comment by Willy-JL** [comment]
Use latest beta, see readme
