### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by PuppyIron** [Willy-JL/F95Checker#179]
Traceback (most recent call last):
  File "F:\Documents\.F95Checker-Beta\modules\utils.py", line 84, in coro_wrapper
    await coro
  File "F:\Documents\.F95Checker-Beta\modules\api.py", line 473, in import_f95_watched_threads
    watched = html.find(parser.is_class("p-body-pageContent")).find(parser.is_class("structItemContainer"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

I'm getting this error in the beta version as well as this

Traceback (most recent call last):
  File "D:\a\F95Checker\F95Checker\modules\utils.py", line 77, in coro_wrapper
  File "D:\a\F95Checker\F95Checker\modules\api.py", line 471, in import_f95_watched_threads
AttributeError: 'NoneType' object has no attribute 'find'

error, which to me seems to be the same issue in the stable branch, if I try importing watched threads.

**Comment by Willy-JL** [comment]
sounds like the ratelimit plague that has happened recently, please try latest beta, a sizeable portion of the backend was remade to accomodate these changes

**Comment by PuppyIron** [comment]
Seems to be working now. Even if slow due to the rate limiting in the API.
