### ISSUE TITLE
not running on sequioa

### ISSUE THREAD

**Issue by drx69** [Willy-JL/F95Checker#181]
Been trying to install on sequioa.  it just starts and stops.  I tried the requirements but brew installs python globally and pip3 wont install anything.  I have been running this in linux for a long time now.  I dont know much about troubleshooting mac apps  so whatever you need, please tell me what you need.

**Comment by Willy-JL** [comment]
there are macos builds provided without python setup required

**Comment by drx69** [comment]
Is it the same as the releases page? Or different? I downloaded the F95Checker-macOS.zip <https://github.com/Willy-JL/F95Checker/releases/download/10.2/F95Checker-macOS.zip> file and that is the one i am having issue with. 10.2 version. should i try an older release?
Get BlueMail <https://bluemail.me> for Desktop
WillyJL wrote:
there are macos builds provided without python setup required

**Comment by Willy-JL** [comment]
i had updated my comment, but you dont see it in email. using github from email is a bad idea overall. anyway, what i said was:

current release is quite old, you should use the beta, check the readme faq for how to do that

**Comment by drx69** [comment]
thanks... ill try to find it and try that.

**Comment by drx69** [comment]
i grabbed build 1220 and downloaded and unzipped macos artifact version.  When i go to run it, macos says it is damaged and to delete it.

**Comment by batblue** [comment]
Check the README. There's an `xattr` command you may have to run on the app to get rid of that message.

**Comment by drx69** [comment]
ok.. thanks...

**Comment by drx69** [comment]
yay... that worked..  Thank you!  Last question and we can close  this:  when do you think the final build be ready?

**Comment by drx69** [comment]
well. almost wroked: 
getting this when i go to refresh... didnt prompt me for user and pass:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 1080, in _wrap_create_connection
  File "uvloop/loop.pyx", line 2084, in create_connection
  File "uvloop/loop.pyx", line 2079, in uvloop.loop.Loop.create_connection
  File "uvloop/sslproto.pyx", line 517, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._do_handshake
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 917, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/work/F95Checker/F95Checker/modules/api.py", line 891, in check_updates
  File "/Users/runner/work/F95Checker/F95Checker/modules/api.py", line 213, in fetch
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 210, in __aenter__
  File "/Users/runner/work/F95Checker/F95Checker/modules/api.py", line 130, in request
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aiohttp/client.py", line 1353, in __aenter__
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aiohttp/client.py", line 657, in _request
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 564, in connect
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 975, in _create_connection
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 1350, in _create_direct_connection
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 1082, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

**Comment by Willy-JL** [comment]
It's funny, because we fixed that just like an hour later than you downloaded your build. Get the new beta xD

And the final build for a proper update will come hopefully within a couple days

**Comment by Willy-JL** [comment]
Login to f95zone is no longer required for the main function of the program. You can disable notification checking in the sidebar, under refresh from what I remember. It is disabled by default now but you had it enabled due to using an older version before.
With that disabled, you will be able to refresh without login. Some functions still require login however, and I'm not sure why the login browser isn't working for you

**Comment by drx69** [comment]
i would love to help troubleshoot this.  I love this on my linux box. I am a terrible coder, but i can test.

**Comment by Willy-JL** [comment]
@batblue does the login webpage work for you?

**Comment by batblue** [comment]
For some reason, I haven't had to log in again in years. But I tried it just now and it didn't. I just got a blank window. The only thing I got in the log was this:

```
Path override failed for key base::DIR_APP_DICTIONARIES and path '/Applications/F95Checker.app/Contents/MacOS/qtwebengine_dictionaries'
```

Not sure what the issue is.

**Comment by Willy-JL** [comment]
if that line in log is the culprit, this wont help, but can y'all try with browser > software webview enabled?

**Comment by drx69** [comment]
no change... and doesnt matter if i chose safari, brave or internal either.

**Comment by batblue** [comment]
Software webview didn't help me either. Interestingly, though, if I open a thread page in the internal browser, I do see the address bar. It's just the page itself that doesn't render.

Not an optimal solution, but what if there were a way for Mac users (and others) to import their f95 cookies? Maybe with the extension, or failing that, from a cookies.txt?

**Comment by Willy-JL** [comment]
interesting... i've setup a macOS Sequoia 15.1.1 VM using [quickemu](https://github.com/quickemu-project/quickemu) on my archlinux laptop (use qubes on desktop and that doesnt support kvm and xen microkernel doesnt run macos vms yet), and running from source the webview opens and loads fine. the app doesnt open normally due to OpenGL not working inside the VM (missing a proper GPU), but launching a webview directly from commandline using same logic the app normally uses, it opens fine. will check on premade builds from github actions next

**Comment by Willy-JL** [comment]
but compiling on macos and running compield version fails. looks like its not just a CI issue, its issue with bundling, getting closer to finding out why then

**Comment by Willy-JL** [comment]
so, the `exe` build has some errors about not being able to find QtWebEngineCore library, but this is gone after building to `app` format. in `app` format, it finds QtWebEngineCore, but then there is `[INFO:web_contents_delegate_qt.cpp(282)] ProcessGone: 3 (11)` in the logs. this sounds like the browser process dies. whats curious is theres no extra information... no message that something went wrong, no crash dump, just seems to die early.

**Comment by Willy-JL** [comment]
even downgrading to an older version of cx_Freeze that we used in the past (6.15.12 and 6.15.5) does not make a difference. im going to give up for now. all i learned is that:
- works fine from source, fails after bundling with cx_Freeze
- it reports `ProcessGone: 3 (11)` where the 3 is `TERMINATION_STATUS_PROCESS_CRASHED` as seen [here](https://github.com/qt/qtwebengine-chromium/blob/b45f07bfbe74c333f1017810c2409e1aa6077a1b/chromium/base/process/kill.h#L26C3-L26C37) and the 11 is the code for the render process crashing, which i have been unable to find any info on, nor trace it back to where this error is thrown in qtwebengine-chromium source code (i got as far as [`OnRenderProcessGone`](https://github.com/qt/qtwebengine-chromium/blob/b45f07bfbe74c333f1017810c2409e1aa6077a1b/chromium/content/browser/renderer_host/render_view_host_impl.cc#L1421-L1439) which takes this exit_code, but i cant find where this is called from)

only other thing i noticed is that i had some code overriding `QTWEBENGINEPROCESS_PATH` when running frozen builds, and the path was outdated (cx_Freeze moved the location of it, i didnt update it in modules/globals.py), but it wouldnt set this when the path did not exist, so currently that code did nothing. i will try fixing it, but from my testing the results remain unchanged.

**Comment by Willy-JL** [comment]
also tried adding all qt plugins to cx_Freeze build, and upgrading qt and cx_Freeze to latest versions, nothing. im nto gonna get anywhere with this.
