### ISSUE TITLE
ClientConnectorSSLError

### ISSUE THREAD

**Issue by DnkKng** [Willy-JL/F95Checker#72]
Trying to refresh produces the following result. I'm not entirely sure, but it seems to have started with version 10.1. Moreover, previously added records are updated correctly, but with a "Misc" type, and the new ones just look like a thread name, with "Unchecked" type
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\asyncio\base_events.py", line 1112, in create_connection
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\asyncio\base_events.py", line 1145, in _create_connection_transport
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\asyncio\sslproto.py", line 574, in _on_handshake_complete
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\asyncio\sslproto.py", line 556, in _do_handshake
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\ssl.py", line 979, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:992)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\F95Checker\F95Checker\modules\utils.py", line 77, in coro_wrapper
  File "D:\a\F95Checker\F95Checker\modules\api.py", line 1028, in refresh
  File "D:\a\F95Checker\F95Checker\modules\api.py", line 673, in full_check
  File "D:\a\F95Checker\F95Checker\modules\api.py", line 200, in fetch
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\contextlib.py", line 204, in __aenter__
  File "D:\a\F95Checker\F95Checker\modules\api.py", line 120, in request
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\aiohttp\client.py", line 536, in _request
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\aiohttp\connector.py", line 540, in connect
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\site-packages\aiohttp\connector.py", line 984, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host attachments.f95zone.to:443 ssl:False [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:992)]
![2023-04-06_115319](https://user-images.githubusercontent.com/130035451/230297757-9aa14521-1792-46be-b6eb-41fe5b2a51d5.jpg)
![2023-04-06_115918](https://user-images.githubusercontent.com/130035451/230297781-34313e74-558e-4aa9-a666-c288c9a92bcf.jpg)

**Comment by FaceCrap** [comment]
If refresh currently fails, and you didn't get prompted to update, get the 10.2 version from the [Latest Release](https://github.com/Willy-JL/F95Checker/releases) page. That version fixes the Misc type and name display. 
I don't know if this also will fix the SSL error, but wouldn't be surprised if it did

**Comment by DnkKng** [comment]
Already have 10.2 version
![изображение](https://user-images.githubusercontent.com/130035451/230822476-54c1dbfb-8c6d-43df-bc37-8b92764f9834.png)
Tried to clear the folder \AppData\Roaming\f95checker, but this only led to the fact that even the old entries stopped refreshing and got type "Uncheked".
![изображение](https://user-images.githubusercontent.com/130035451/230823059-46a88a80-90b2-4774-a695-8a3055770b64.png)

**Comment by DnkKng** [comment]
Tried to downgrade until version 9.6.2, didn't work.
I am not an expert in Python, a simple search shows that the error may be in aiohttp module
https://github.com/aio-libs/aiohttp/issues/4536#issuecomment-579740877

**Comment by Willy-JL** [comment]
that error means that the server we are connecting to has too old of a ssl version. i can connect to f95zone just fine. what this leads me to believe is that you have an issue with your ISP, DNS or something else. do you normally use a VPN to browse f95zone? anything weird you do normally? either way this is not an issue with f95checker
